package internal

import "testing"

func TestPart1Example(t *testing.T) {

	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`
	expectedAcc := 21
	acc, _ := Do(input)
	if acc != expectedAcc {
		t.Logf("expected %d, got %d", expectedAcc, acc)
		t.Fail()
	}
}

func TestPart1Basic1(t *testing.T) {

	input := `.......S.......
...............
.......^.......
...............`
	expectedAcc := 1
	acc, _ := Do(input)
	if acc != expectedAcc {
		t.Logf("expected %d, got %d", expectedAcc, acc)
		t.Fail()
	}
}

func TestPart1Basic2(t *testing.T) {

	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............`
	expectedAcc := 3
	acc, _ := Do(input)
	if acc != expectedAcc {
		t.Logf("expected %d, got %d", expectedAcc, acc)
		t.Fail()
	}
}

func TestPart2Example(t *testing.T) {

	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`
	expectedAcc := 40
	_, acc := Do(input)
	if acc != expectedAcc {
		t.Logf("expected %d, got %d", expectedAcc, acc)
		t.Fail()
	}
}

func TestPart2Basic1(t *testing.T) {

	input := `.......S.......
...............
.......^.......
...............`
	expectedAcc := 2
	_, acc := Do(input)
	if acc != expectedAcc {
		t.Logf("expected %d, got %d", expectedAcc, acc)
		t.Fail()
	}
}
